routes/web.php
<?php

use App\Http\Controllers\AdvancePaymentController;
use App\Http\Controllers\AssignPlanController;
use App\Http\Controllers\BankDetailController;
use App\Http\Controllers\Billing\BillController;
use App\Http\Controllers\Billing\GeneratedPdfController;
use App\Http\Controllers\Billing\PropertyBillController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Collections\PaymentCodeController;
use App\Http\Controllers\Collections\PaymentPlanController;
use App\Http\Controllers\Collections\PaymentTypeController;
use App\Http\Controllers\ComplainController;
use App\Http\Controllers\ComplainTypeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Entry_type\EntryTypeController;
use App\Http\Controllers\GoverningBodyController;
use App\Http\Controllers\MemberShipController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\POSController;
use App\Http\Controllers\Properties\PropertyController;
use App\Http\Controllers\Property\AreaUnitController;
use App\Http\Controllers\Property\BlockController;
use App\Http\Controllers\Property\CityController;
use App\Http\Controllers\Property\DocumentTypeController;
use App\Http\Controllers\Property\PropertyTypeController;
use App\Http\Controllers\Property\SocietyController;
use App\Http\Controllers\ReportController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ServicesBillController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\TransferController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard');
// Profile
Route::get('profile', 'DashboardController@profile');
Route::post('updateUserProfile', 'DashboardController@updateUserProfile');

// Role
Route::resource('roles', RoleController::class);
// Permission
Route::resource('permissions', PermissionController::class);

// Route accessed only by admin
// Route::group(['middleware' => 'admin'], function () {
// Users
Route::resource('users', UserController::class);
// PROPERTY SETUP
Route::resource('property/city', CityController::class);
Route::resource('property/society', SocietyController::class);
Route::resource('property/block', BlockController::class);
Route::resource('property/property-types', PropertyTypeController::class);
Route::resource('property/doc-types', DocumentTypeController::class);
Route::resource('property/area-units', AreaUnitController::class);
// TRANSFER PROPERTY
Route::resource('transfer-property/List', TransferController::class);
Route::resource('transfer-property/Add', TransferController::class);
// Maintenance
Route::resource('maintenance/categories', CategoryController::class);
Route::resource('maintenance/services', ServiceController::class);
// POS
Route::resource('pos', POSController::class);
Route::get('pos/{id}/show', [POSController::class, 'show']);
// GOVERNING-BODY
Route::resource('/governing-body', GoverningBodyController::class);
Route::post('/governing-body/{id}/status', [GoverningBodyController::class, 'status']);
// STAFF
Route::resource('/staff', StaffController::class);
//  ERP ENTRY-TYPES
Route::resource('entry_type/entry-list', EntryTypeController::class);
Route::resource('entry_type/entry-add', EntryTypeController::class);
// COMPLAIN TYPES
Route::resource('/complain-types', ComplainTypeController::class);
// });

Route::get('/notification', function () {
    return view('admin.notifications.notification');
});

require __DIR__ . '/auth.php';
// PROPERTIES
Route::resource('properties/list', PropertyController::class);
Route::post('properties/add/{id}/edit', [PropertyController::class, 'view']);
Route::post('properties/add/{id}/doc', [PropertyController::class, 'addDocument']);
Route::resource('properties/add', PropertyController::class);
Route::get('/download-image/{filename}', [PropertyController::class, 'downloadImage'])->name('download.image');
// Billing
Route::resource('billing/monthly-bills', PropertyBillController::class);
Route::get('billing/monthly-bills-get-plans/{id}', [PropertyBillController::class, 'get_plans']);
Route::resource('billing/property-bills', BillController::class);
Route::post('billing/property-bills/{id}/verify-payment', [BillController::class, 'verify_payment']);
Route::resource('billing/service-bills', ServicesBillController::class);
Route::post('billing/service-bills/{id}/verify-payment', [ServicesBillController::class, 'verify_payment']);
Route::resource('billing/bill-pdf', GeneratedPdfController::class);
Route::resource('billing/advance-payment', AdvancePaymentController::class);
// COLLECTIONS
Route::resource('collections/payment-type', PaymentTypeController::class);
Route::post('collections/payment-type/{id}/status', [PaymentTypeController::class, 'status']);
Route::resource('collections/payment-code', PaymentCodeController::class);
Route::post('collections/payment-code/{id}/status', [PaymentCodeController::class, 'status']);
Route::resource('collections/payment-plan', PaymentPlanController::class);
Route::resource('collections/payment-code', PaymentCodeController::class);
Route::post('collections/payment-plan/{id}/status', [PaymentPlanController::class, 'status']);
Route::resource('collection/assign-plan', AssignPlanController::class);
// MEMBER-SHIP
Route::resource('member_ship/member_list', MemberShipController::class);
Route::post('member_ship/member_list/{id}/status', [MemberShipController::class, 'destroy']);
Route::resource('member_ship/member_add', MemberShipController::class);
// BANK
Route::resource('billing/bank', BankDetailController::class);
// COMPLAINS
Route::resource('/complains', ComplainController::class);

// Services
Route::post('/pos/addtocart', [POSController::class, 'addToCart']);
Route::post('/pos/updateQuantity/{id}', [POSController::class, 'updateQuantity']);

//Reports
Route::get('property_ledger', [ReportController::class, 'index']);
Route::get('monthly_maintenance_bill_report', [ReportController::class, 'monthly_maintenance_bill_report'])->name('monthly_maintenance_bill_report');

app/Http/Controllers/Entry_type/EntryTypeController.php
<?php

namespace App\Http\Controllers\Entry_type;

use App\Http\Controllers\Controller;
use App\Http\Requests\EntryTypeRequest;
use App\Models\EntryType;
use App\Models\EntryTypeDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Yajra\DataTables\Facades\DataTables;

class EntryTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->getPathInfo() == '/entry_type/entry-list') {
            if ($request->ajax()) {
                return DataTables::of(EntryType::query())->make(true);
            }
            return view('admin.Entry_type.entry_list');
        }
        if ($request->getPathInfo() == '/entry_type/entry-add') {
            $curl = curl_init();
            curl_setopt_array($curl, array(
                CURLOPT_URL => 'http://194.163.145.90/eperp/api/getGlAccounts?data=gl_codes',
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_ENCODING => '',
                CURLOPT_MAXREDIRS => 10,
                CURLOPT_TIMEOUT => 0,
                CURLOPT_FOLLOWLOCATION => true,
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                CURLOPT_CUSTOMREQUEST => 'GET',
                CURLOPT_HTTPHEADER => array(
                    'Cookie: ci_session=a32r6av7gph2s93g40bgo2a6dqe628ac'
                ),
            ));
            $response = curl_exec($curl);
            curl_close($curl);
            $gl_entries = json_decode($response);
            return view('admin.Entry_type.entry_add', ['gl_code' => $gl_entries->data]);
        }
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(EntryTypeRequest $request)
    {
        try {
            DB::transaction(function () use ($request) {
                $entry = new EntryType();
                $entry->type = $request->type;
                $entry->description = $request->description;
                $entry->save();
                $id = DB::table('entry_types')->latest('id')->pluck('id');
                foreach ($request->erp_loop as $erp) {
                    $data = explode('|', $erp['gl_code']);
                    $code = (int)$data[0];
                    $string = $data[1];
                    $detail = new EntryTypeDetail();
                    $detail->entry_type_id = (int)$id->first();
                    $detail->gl_code = $code;
                    $detail->gl_name = $string;
                    $detail->method = $erp['method'];
                    $detail->description = $erp['erp-description'];
                    $detail->save();
                }
                return ['code' => '200', 'message' => 'success'];
            });
        } catch (\Exception | ValidationException $e) {
            if ($e instanceof ValidationException) {
                return ['code' => '422', 'errors' => $e->errors()];
            } else {
                DB::rollBack();
                return ['code' => '500', 'error_message' => $e->getMessage()];
            }
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $erp = EntryType::findOrFail($id);
        $erp_details = DB::table('entry_type_details')->where('entry_type_id', $id)->get();
        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_URL => 'http://194.163.145.90/jchserp/api/getGlAccounts?data=gl_codes',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'GET',
            CURLOPT_HTTPHEADER => array(
                'Cookie: ci_session=a32r6av7gph2s93g40bgo2a6dqe628ac'
            ),
        ));
        $response = curl_exec($curl);
        curl_close($curl);
        $gl_entries = json_decode($response);
        return view('admin.Entry_type.entry_edit', ['erp' => $erp, 'details_loop' => $erp_details, 'gl_code' => $gl_entries->data]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $item = DB::table('entry_type_details')->where('entry_type_id', $id)->get();
        return response([
            'data' => $item,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(EntryTypeRequest $request, string $id)
    {
        try {
            DB::transaction(function () use ($request, $id) {
                $entry = EntryType::findOrFail($id);
                $entry->type = $request->type;
                $entry->description = $request->description;
                $entry->save();
                DB::table('entry_type_details')->where('entry_type_id', $id)->delete();
                foreach ($request->erp_loop as $erp) {
                    $data = explode('|', $erp['gl_code']);
                    $code = (int)$data[0];
                    $string = $data[1];
                    $detail = new EntryTypeDetail();
                    $detail->entry_type_id = $id;
                    $detail->gl_code = $code;
                    $detail->gl_name = $string;
                    $detail->method = $erp['method'];
                    $detail->description = $erp['erp-description'];
                    $detail->save();
                }
                return ['code' => '200', 'message' => 'success'];
            });
        } catch (\Exception | ValidationException $e) {
            if ($e instanceof ValidationException) {
                return ['code' => '422', 'errors' => $e->errors()];
            } else {
                DB::rollBack();
                return ['code' => '500', 'error_messgae' => $e->getMessage()];
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/Entry_type/entry_list.blade.php
@extends('admin.layouts.master')
@section('title', 'List')
@section('content')
    <section id="basic-datatable">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-start mb-0">Entry Types</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a>
                                </li>
                                <li class="breadcrumb-item active">Entry-Types
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <table class="datatables-basic table" id="dataTable">
                        <thead>
                            <tr>
                                <th></th>
                                <th>id</th>
                                <th>Type</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <div class="vertical-modal-ex">
        <!-- Modal -->
        <div class="modal fade" id="erp-details" tabindex="-1" aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle">ERP ENTRY TYPE DETAILS</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>GL-CODE</th>
                                    <th>GL NAME</th>
                                    <th>CR/DR</th>
                                    <th>DESCRIPTION</th>
                                </tr>
                            </thead>
                            <tbody id="entry_type_details">
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('custom-scripts-foot')
    @if (Session::has('success_message'))
        <script>
            Toast.fire({
                icon: "success",
                title: "{!! Session::get('success_message') !!}"
            })
        </script>
    @endif
    @if (Session::has('error_message'))
        <script>
            Toast.fire({
                icon: "warning",
                title: "{!! Session::get('error_message') !!}"
            })
        </script>
    @endif
    <script>
        var Table = '';
        $(document).ready(function() {
            Table = $('#dataTable').DataTable({
                // processing: true,
                // serverSide: true,
                ajax: '{!! route('entry-list.index') !!}',
                columns: [{
                        data: 'responsive_id'
                    },
                    {
                        data: 'id'
                    },
                    {
                        data: 'type'
                    },
                    {
                        data: 'description'
                    },
                    {
                        data: ''
                    }
                ],
                columnDefs: [{
                        // For Responsive
                        className: 'control',
                        orderable: false,
                        searchable: false,
                        targets: 0
                    },
                    {
                        // Actions
                        targets: -1,
                        title: 'Actions',
                        orderable: false,
                        searchable: false,
                        render: function(data, type, full, meta) {
                            let btn = '';
                            @can('erp_entry_type_edit')
                                btn +=
                                    `<a href="{{ url('entry_type/entry-list/${full.id}') }}" class="item-edit">` +
                                    feather.icons['edit'].toSvg({
                                        class: 'font-medium-4'
                                    }) +
                                    '</a>';
                            @endcan
                            @can('erp_entry_type_view')
                                btn += '<a href="javascript:;" onclick="view_item(' + full
                                    .id +
                                    ')">' +
                                    feather.icons['eye'].toSvg({
                                        class: 'font-medium-4 text-success'
                                    }) +
                                    '</a>';
                            @endcan

                            return btn;
                        }
                    },
                    {
                        "defaultContent": "-",
                        "targets": "_all"
                    }
                ],
                order: [
                    [1, 'asc']
                ],
                dom: '<"card-header border-bottom p-1"<"head-label"><"dt-action-buttons text-end"B>><"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 pb-1 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
                displayLength: 7,
                lengthMenu: [7, 10, 25, 50, 75, 100],
                buttons: [{
                        extend: 'collection',
                        className: 'btn btn-outline-secondary dropdown-toggle me-2',
                        text: feather.icons['share'].toSvg({
                            class: 'font-small-4 me-50'
                        }) + 'Export',
                        buttons: [{
                                extend: 'print',
                                text: feather.icons['printer'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Print',
                                className: 'dropdown-item',
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'csv',
                                text: feather.icons['file-text'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Csv',
                                className: 'dropdown-item',
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'excel',
                                text: feather.icons['file'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Excel',
                                className: 'dropdown-item',
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'pdf',
                                text: feather.icons['clipboard'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Pdf',
                                className: 'dropdown-item',
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            },
                            {
                                extend: 'copy',
                                text: feather.icons['copy'].toSvg({
                                    class: 'font-small-4 me-50'
                                }) + 'Copy',
                                className: 'dropdown-item',
                                exportOptions: {
                                    columns: ':not(.not_include)'
                                }
                            }
                        ],
                        init: function(api, node, config) {
                            $(node).removeClass('btn-secondary');
                            $(node).parent().removeClass('btn-group');
                            setTimeout(function() {
                                $(node).closest('.dt-buttons').removeClass('btn-group')
                                    .addClass('d-inline-flex');
                            }, 50);
                        }
                    },
                    @can('erp_entry_type_add')
                        {
                            text: feather.icons['plus'].toSvg({
                                class: 'me-50 font-small-4'
                            }) + 'ADD ENTRY TYPE',
                            className: 'create-new btn btn-primary erp',
                            attr: {

                            },
                            init: function(api, node, config) {
                                $(node).removeClass('btn-secondary');
                            }
                        }
                    @endcan
                ],
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.childRowImmediate,
                        type: 'column',
                    }
                },
                language: {
                    paginate: {
                        // remove previous & next text from pagination
                        previous: '&nbsp;',
                        next: '&nbsp;'
                    }
                }
            });

            $(document).on('click', '.erp', function() {
                var anchor = $('<a>', {
                    href: '{{ route('entry-add.index') }}',
                    style: 'display:none;'
                });

                $('body').append(anchor);

                anchor[0].click();

                anchor.remove();
            });

            $('div.head-label').html('<h6 class="mb-0">List of Entry Types</h6>');
        });

        function view_item(id) {
            $('#erp-details').modal('show');
            let itemId = id;
            $.ajax({
                url: "{{ url('/entry_type/entry-list') }}" + "/" + itemId + "/edit",
                method: 'GET',
                success: function(response) {
                    $("#entry_type_details tr").remove();
                    table = $('#entry_type_details');
                    $.each(response.data, function(index, item) {
                        var row = $('<tr>');
                        row.append('<td>' + item.gl_code + '</td>');
                        row.append('<td>' + item.gl_name + '</td>');
                        row.append('<td>' + item.method + '</td>');
                        row.append('<td>' + item.description + '</td>');
                        table.append(row);
                    });
                },
                error: function(xhr) {}
            });
        }
    </script>
@endsection